### ISSUE TITLE
Using non built-in packages and sending/receiving audio data

### ISSUE THREAD

**Issue by KianRK** [ros2-dotnet/ros2_dotnet#118]
Hi, I am trying to send and receive audio data from and to a Hololens 2. Am I assuming correctly that I cannot use the audio_common pkg from withing Unity with this project?

Is there a suggested way to realize audio transfer within ros2_dotnet or would you recommend to find another solution for that task?

**Comment by hoffmann-stefan** [comment]
Hi @KianRK,

sorry for the late reply, but was busy at work and spare time recently.

I don't know of any, but haven't worked with audio in ROS and Hololens/Unity either.

But as far as I understand this `audio_common` provides interfaces to send audio data over ROS topics.
Using those messages in `ros2_dotnet` would be like any other messages, just compile them in the ros2_dotnet_workspace like the other standard or your custom ones. Then you would need to subscribe to those topics and pass the audo data to Unity/UWP. Though as said above I don't have any background on this, nor do I have any further pointers to libraries, docs or tutorials.

Will close this issue as it is more a question on how to use `ros2_dotnet` and audio support is out of scope for this exact library.
