### ISSUE TITLE
Is composite types still missing?

### ISSUE THREAD

**Issue by mce16** [ros2-dotnet/ros2_dotnet#71]
Hi

I would like to use some msg types such as

```
Data.msg:

int32 d_value
float32 f_value

Test.msg:
test_msgs/Data data1
```

Is this possible yet?

I saw in another thread array types #62 that fmrico has completed the array and nested types. Is this the same as what i mentioned here? How do i get a build of that, i would very much like to try it. I am running on Windows 10 x64

**Comment by fmrico** [comment]
Composite (Nested) types are currently available. Collections (Arrays) are still under revision.

**Comment by hoffmann-stefan** [comment]
Closing this as nested types are already avaliable.
